In [2]:
import numpy as np
a=np.array([[1,2,4,57,8],[2,4,75,5,3]])
print(a)
print(a.ndim)

[[ 1  2  4 57  8]
 [ 2  4 75  5  3]]
2


In [2]:
print(a[0])

1


In [4]:
b=np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]


In [4]:
c=np.full((2,2),6)
print(c)

[[6 6]
 [6 6]]


In [6]:
d=np.linspace(2,8,5)
print(d)

[2.  3.5 5.  6.5 8. ]


In [7]:
e=np.random.random(5)
print(e)

[0.20622879 0.47525342 0.26401855 0.60553527 0.72493217]


In [9]:
f=np.random.randint(2,10,2)
print(f)

[6 4]


In [11]:
print(b.shape)


(2, 2)


In [13]:
print(b.size)

4


In [14]:
print(b.itemsize)

8


In [5]:
print(b.ndim)

2


In [16]:
print(c.dtype)

int32


In [21]:
g=c.astype('int8')

In [22]:
print(g.dtype)

int8


In [26]:
np.subtract(5,4)

1

In [27]:
np.divide(8,2)

4.0

In [28]:
np.sqrt(2)

1.4142135623730951

In [30]:
np.sin(0)

0.0

In [31]:
np.cos(90)

-0.4480736161291701

In [32]:
np.std(a)

25.339494864736352

In [34]:
h=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
np.vstack([a,h])

array([[ 1,  2,  4, 57,  8],
       [ 2,  4, 75,  5,  3],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
np.hstack([a,h])

array([[ 1,  2,  4, 57,  8,  1,  2,  3,  4,  5],
       [ 2,  4, 75,  5,  3,  6,  7,  8,  9, 10]])

In [45]:
np.ravel(a)

array([ 1,  2,  4, 57,  8,  2,  4, 75,  5,  3])

In [51]:
print(h[0:2,3])

[4 9]


In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8],[8,9,0,3]])
print(arr[0:2,2])

[3 7]


In [53]:
i=np.min(arr)
print(i)

0


In [54]:
j=np.max(arr)
print(j)

9


In [8]:
k=np.max(arr,axis=1)
print(k)

[4 8 9]
